### ISSUE TITLE
Support Symfony 3

### ISSUE THREAD

**Issue by geekdevs** [mathewpeterson/EmailTemplateBundle#6]
Please add support for symfony 3 into composer

**Comment by geekdevs** [comment]
@mathewpeterson ping?
This package only depends on symfony framework bundle directly so simply updating to v.3.0 in composer is pretty simple. And all tests are passing

**Comment by geekdevs** [comment]
@mathewpeterson is this project still maintained?

**Comment by mathewpeterson** [comment]
No, I haven't done much Symfony stuff in a while now.

**Comment by geekdevs** [comment]
I have just noticed that support of symfony3 was added to this repo in master.
@mathewpeterson would you please add a new release to this repo so that it could be used through composer?

**Comment by geekdevs** [comment]
@mathewpeterson please, please release current version so that we could use symfony 3 without hacking with commit hashes. It's really not that hard

**Comment by mathewpeterson** [comment]
Sorry for the lack of updates. I've tagged a new version though I don't have any to test it.
